spring:
  application:
    name: kafka-demo
  mail:
    username: 13774495234@163.com
    password: LAUJOQUOFNXKXJQT
    host: smtp.163.com
  kafka:
    bootstrap-servers: 192.168.3.19:9092
    admin:
      properties:
        bootstrap-servers: 192.168.3.19:9092
        client.id: admin-client
      topic.metadata.refresh.interval.ms: 5000
      topic.metadata.max.age.ms: 15000
      topic-properties:
        test: cleanup.policy=compact,segment.ms=10000
    consumer:
      group-id: my-group
server:
  port: 9101
