spring:
  application:
    name: kafka-demo
  mail:
    username: 13774495234@163.com
    password: LAUJOQUOFNXKXJQT
    host: smtp.163.com
  kafka:
    bootstrap-servers: 192.168.3.18:9092
    consumer:
      group-id: my-group
server:
  port: 9101
